spring.application.name=tasks-user

# Keycloak
keycloak.realm=master
keycloak.auth-server-url=http://localhost:8082/
keycloak.resource=tasks
keycloak.credentials.secret=E7acfb9LC1vF0NEFAwne4dribRqRX8wO

server.port=10000
