spring.application.name=tasks-tasks
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_REALM_CERT_URL:http://localhost:8484/auth/realms/master/protocol/openid-connect/certs}
spring.data.mongodb.host=localhost
spring.data.mongodb.port=8091
spring.data.mongodb.database=tasks